language: java
sudo: required
dist: trusty
jdk:
- openjdk8
after_success:
- if [[ $TRAVIS_BRANCH == master ]]; then ./gradlew uploadArchives; fi
# if this is actually a commit to master and not a pull request build into master, then publish master-snapshot
- if [[ $TRAVIS_BRANCH == master && $TRAVIS_PULL_REQUEST == false ]]; then
    git tag master;
    ./gradlew uploadArchives;
  fi
